### ISSUE TITLE
Overall design discussion.

### ISSUE THREAD

**Issue by bliti** [nvquanghuy/texpaste#1]
I'd like to get your input regarding the front end design of the application. We all agree it is a bit too gray as it stands. I have been thinking about it, and some ideas have appeared. But I'm interested in what you have to say.

Not that I am not focused on changing the layout itself, just make it easier on the eyes.

**Comment by nvquanghuy** [comment]
Thanks @bliti. I really don't have any idea in mind about color and theme - but I agree it should somehow be easier on the eyes.

Also it seems majority of feedback at the moment focus more on Usability of the app rather than colourish. You can see some of these below: http://www.reddit.com/r/math/comments/1lpy5r/share_pastebin_for_mathematics_notes_made_this/cc1llxp

1/ Small-ness of the symbol-selection list.
2/ The width of the typing area and the render area
